version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: sumanth
      WORDPRESS_DB_PASSWORD: admin
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: sumanth
      MYSQL_PASSWORD: admin
      MYSQL_RANDOM_ROOT_PASSWORD: 1 # removed quotes here
    volumes:
      - db:/var/lib/mysql
    expose:
      - 3306
      - 33060

volumes:
  wordpress:
  db:
